- name: installing apache2
  become: true
  apt: pkg=apache2 state=latest update_cache=true

- name: copy ports config
  become: true
  template: src=apache2.ports.conf dest=/etc/apache2/ports.conf
  notify: restart apache2

- name: copy site default config
  become: true
  replace:
    path=/etc/apache2/sites-enabled/000-default.conf
    regexp="^<VirtualHost *:80>"
    replace="<VirtualHost *:8080>"
  notify: restart apache2

- name: enabled mod_rewrite
  become: true
  apache2_module: name=rewrite state=present
  notify: restart apache2

- name: enabled mod_php
  become: true
  apache2_module: name=php7.0 state=present
  notify: restart apache2
