- name: add apt key for Ondrej PHP PPA
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 14aa40ec0831756756d7f66c4f4ea0aae5267a6c

- name: install Ondrej PHP PPA
  apt_repository: repo='ppa:ondrej/php' update_cache=yes

- name: installing php
  apt: pkg={{ item }} state=latest update_cache=true
  with_items:
    - php{{php_ver}}
    - php{{php_ver}}-mysql
    - libapache2-mod-php{{php_ver}}
