- name: specify mysql root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: confirm mysql root password before installing
  debconf: name='mysql-server' question='mysql-server/root_password_again' value='{{mysql_root_password | quote}}' vtype='password'
  become: true

- name: install mysql packages
  apt: pkg={{ item }} state=installed
  become: true
  with_items:    
   - python-mysqldb
   - mysql-client
   - mysql-common
   - mysql-server
