---
- name: create mysql database
  mysql_db: 
    name={{ mysql_wp_db }} 
    state=present
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}

- name: create mysql user
  mysql_user: 
    name={{ mysql_wp_user }} 
    password={{ mysql_wp_pwd }} 
    priv={{ mysql_wp_db }}.*:ALL
    login_user={{ mysql_root_user }}
    login_password={{ mysql_root_password }}
