- name: add apt key Nginx Stable PPA
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 8b3981e7a6852f782cc4951600a6f0a3c300ee8c

- name: install Nginx Stable PPA
  apt_repository: repo='ppa:nginx/stable' update_cache=yes

- name: installing nginx
  apt: pkg=nginx state=latest update_cache=true

- name: copy frontend config
  template:
    src: nginx.frontend.conf
    dest: /etc/nginx/conf.d/frontend.conf

- name: change upstream in nginx wp config
  lineinfile:
    dest: /etc/nginx/conf.d/frontend.conf
    regexp: "upstream front"
    line: "{{upstream_front_servers}}"
  notify: restart nginx

- name: change wp site in nginx config
  lineinfile:
    dest: /etc/nginx/conf.d/frontend.conf
    regexp: "server_name"
    line: "        server_name {{http_wp_server_name}};"
  notify: restart nginx

- name: restart nginx
  service:
    name: nginx
    state: restarted
